'use strict'
Object.defineProperty(exports, '__esModule', { value: true })

const ABIDAPP = [
  {
    type: 'constructor',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint256', name: 'inittialPrice_', internalType: 'uint256' },
      { type: 'address', name: 'usdToken', internalType: 'address' },
      { type: 'address', name: 'htgToken', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'admin',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256[]', name: 'amounts', internalType: 'uint256[]' }],
    name: 'amountsOut',
    inputs: [
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'buyHTG',
    inputs: [{ type: 'uint256', name: 'usd', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeAdmin',
    inputs: [{ type: 'address', name: 'admin_', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeFee',
    inputs: [{ type: 'uint256', name: 'fee_', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeHTG',
    inputs: [{ type: 'address', name: 'htgToken', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeManager',
    inputs: [{ type: 'address', name: 'manager_', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeOwner',
    inputs: [{ type: 'address', name: 'owner_', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changePriceSOS',
    inputs: [{ type: 'uint256', name: 'pricce_', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeRouter',
    inputs: [{ type: 'address', name: 'routerAddr', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeUSD',
    inputs: [{ type: 'address', name: 'usdToken', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'changeWETH',
    inputs: [{ type: 'address', name: 'wethAddr', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'div',
    inputs: [
      { type: 'uint256', name: 'a', internalType: 'uint256' },
      { type: 'uint256', name: 'b', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'emergencyWithdraw',
    inputs: [{ type: 'address', name: 'recipient', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'fees',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getHTGReserve',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getUSDReserve',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'manager',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'pure',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'mul',
    inputs: [
      { type: 'uint256', name: 'a', internalType: 'uint256' },
      { type: 'uint256', name: 'b', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'owner',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'price',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'sellHTG',
    inputs: [{ type: 'uint256', name: 'tokens', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'sendHTG',
    inputs: [
      { type: 'address', name: 'from', internalType: 'address' },
      { type: 'address', name: 'to', internalType: 'address' },
      { type: 'uint256', name: 'tokens', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'setPausable',
    inputs: [{ type: 'bool', name: 'pause_', internalType: 'bool' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'swap',
    inputs: [
      { type: 'address', name: 'tok_in', internalType: 'address' },
      { type: 'address', name: 'tok_out', internalType: 'address' },
      { type: 'address[]', name: 'path', internalType: 'address[]' },
      { type: 'uint256', name: 'amount', internalType: 'uint256' },
    ],
  },
]

// exports.default = { pancakeSwapAbi, tokenAbi }
module.exports = { ABIDAPP }
